import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service · Margot",
  description:
    "Terms governing your use of Margot — account terms, subscription billing, acceptable use, content ownership, and limitations of liability.",
  alternates: { canonical: "/terms" },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "21 July 2026";

export default function TermsPage() {
  return (
    <main className="bg-bg text-ink min-h-screen px-6 py-[clamp(48px,7vw,96px)]">
      <article className="max-w-[760px] mx-auto">
        <Link
          href="/"
          className="font-sans text-[12px] font-medium tracking-tight7 text-ink3 hover:text-ink no-underline"
        >
          ← Back to Margot
        </Link>

        <header className="mt-8 mb-12">
          <h1 className="font-display font-normal text-ink opsz-144 m-0 text-[clamp(36px,5vw,60px)] leading-[1.05] tracking-tight2">
            Terms of <em>Service</em>
          </h1>
          <p className="mt-3 font-sans text-[13px] text-ink3 tracking-tight7">
            Last updated: {LAST_UPDATED}
          </p>
        </header>

        <Section>
          <P>
            These Terms of Service ("Terms") govern your use of <Strong>Margot</Strong>, a
            mobile application operated by YAVREN ("we", "us", "our"). By
            creating an account, downloading, or otherwise using Margot (the "App"), you agree to
            be bound by these Terms. If you do not agree, do not use the App.
          </P>
          <P>
            These Terms work alongside our{" "}
            <Link href="/privacy" className="underline hover:text-peach">
              Privacy Policy
            </Link>
            , which explains how we handle your personal data. The Privacy Policy is
            incorporated into these Terms by reference.
          </P>
        </Section>

        <Hr />

        <Section title="1. The service">
          <P>
            Margot helps you digitise your wardrobe, plan outfits, and decide whether new clothing
            items fit your existing closet. We may add, remove, or modify features at any time
            without notice.
          </P>
          <P>
            Margot's outfit recommendations, sustainability scores, cost-per-wear estimates, and
            styling rules are generated by software, including third-party model providers.{" "}
            <Strong>
              All recommendations are suggestions, not professional advice.
            </Strong>{" "}
            You remain solely responsible for your purchasing, styling, and disposal
            decisions.
          </P>
        </Section>

        <Section title="2. Eligibility and account">
          <P>
            You must be at least 13 years old to use Margot. If you are under 18, you may
            use the App only with the involvement and consent of a parent or legal guardian.
          </P>
          <P>
            You are responsible for the accuracy of the information you provide and for
            keeping your account credentials confidential. You agree to notify us promptly
            of any unauthorised access at{" "}
            <a href="mailto:margot@margotwardrobe.com" className="underline hover:text-peach">
              margot@margotwardrobe.com
            </a>
            .
          </P>
          <P>
            You may sign in with email, Google, or Apple. You may close your account at any
            time from <em>Settings → Privacy → Delete account</em>. Deletion is permanent
            and irreversible — see Section 8 below.
          </P>
        </Section>

        <Hr />

        <Section title="3. Subscriptions and billing">
          <Sub title="3.1 Margot Premium">
            <P>
            Margot offers a paid subscription called <Strong>Margot Premium</Strong>. The
            available plans, their prices, and their billing periods are shown inside the App
            before you confirm purchase, in your local currency as presented by Apple. Margot
            Premium supports <em>Apple Family Sharing</em>.
            </P>
          </Sub>

          <Sub title="3.2 Apple-managed billing">
            <P>
              All subscriptions are sold and managed through the Apple App Store. Payment
              is charged to your Apple ID account at the start of each billing period.
              Your Apple{" "}
              <a
                href="https://www.apple.com/legal/internet-services/itunes/"
                className="underline hover:text-peach"
                target="_blank"
                rel="noopener noreferrer"
              >
                Media Services Terms
              </a>{" "}
              also apply to your subscription.
            </P>
          </Sub>

          <Sub title="3.3 Automatic renewal">
            <P>
              Your subscription renews automatically at the end of each billing period
              unless you cancel at least 24 hours before the end of the current period.
              Renewal will be charged at the then-current rate (typically the same price,
              but Apple may charge a different amount if local taxes change).
            </P>
            <P>
              You can cancel anytime in your Apple ID settings:{" "}
              <em>Settings → [your name] → Subscriptions → Margot Premium</em>. We do not
              receive your payment details and cannot cancel your subscription on your
              behalf.
            </P>
          </Sub>

          <Sub title="3.4 Refunds">
            <P>
              All purchase refunds are handled by Apple under their{" "}
              <a
                href="https://reportaproblem.apple.com"
                className="underline hover:text-peach"
                target="_blank"
                rel="noopener noreferrer"
              >
                refund policy
              </a>
              . We do not have access to your payment information and cannot issue refunds
              directly.
            </P>
          </Sub>

          <Sub title="3.5 Subscription content">
            <P>
              We may change which features are part of the free tier vs Margot Premium at
              any time. Features available at purchase that later move behind Premium
              remain available for the duration of your then-current billing period.
            </P>
          </Sub>
        </Section>

        <Hr />

        <Section title="4. Your content">
          <P>
            You retain ownership of the photos, descriptions, and other content you add to
            Margot (collectively, "Your Content"). By using the App, you grant us a
            limited, worldwide, royalty-free licence to host, process, and display Your
            Content solely for the purpose of operating and improving the App for you.
            This licence ends when you delete the content or your account.
          </P>
          <P>
            You are responsible for ensuring you have the right to upload Your Content. Do
            not upload images you do not own or are not authorised to share.
          </P>
        </Section>

        <Section title="5. Acceptable use">
          <P>You agree not to use Margot to:</P>
          <Ul>
            <Li>upload content that is illegal, infringing, defamatory, or hateful;</Li>
            <Li>
              attempt to reverse-engineer, decompile, scrape, or interfere with the App's
              normal operation;
            </Li>
            <Li>
              circumvent rate limits, abuse the AI features, or attempt to exhaust our
              resources;
            </Li>
            <Li>
              impersonate another person, share another user's content without consent, or
              harass other users;
            </Li>
            <Li>
              probe, scan, or test the vulnerability of the App or its underlying
              infrastructure without written authorisation.
            </Li>
          </Ul>
          <P>
            We may suspend or terminate accounts that violate these rules, without notice
            in serious cases.
          </P>
        </Section>

        <Hr />

        <Section title="6. AI-generated content">
          <P>
            Margot uses generative AI to suggest outfits, evaluate purchases, and surface
            wardrobe insights. AI outputs are statistical guesses — they may be incorrect,
            biased, or inconsistent with your taste. We make no warranty as to the
            accuracy, suitability, or completeness of AI-generated content.
          </P>
          <P>
            You should treat AI outputs as starting points, not final answers, especially
            for purchasing decisions, resale pricing, or sustainability claims.
          </P>
        </Section>

        <Section title="7. Third-party services">
          <P>
            Margot relies on third-party providers to function (e.g. cloud hosting,
            authentication, AI models, payment processing, weather data). Your use of the
            App is also subject to the terms of those providers where their service is
            invoked. We are not responsible for the content, accuracy, or availability of
            third-party services.
          </P>
        </Section>

        <Hr />

        <Section title="8. Account deletion and data retention">
          <P>
            You can permanently delete your Margot account from{" "}
            <em>Settings → Privacy → Delete account</em>. Deletion immediately removes
            your profile, wardrobe items, outfits, calendar data, OOTD posts, scans, and
            associated photos. This action <Strong>cannot be undone</Strong>.
          </P>
          <P>
            We may retain anonymised, aggregated usage statistics that no longer identify
            you (e.g. AI request logs with the user identifier removed) for service
            improvement and abuse monitoring.
          </P>
        </Section>

        <Section title="9. Disclaimers">
          <P>
            <Strong>The App is provided "as is" and "as available".</Strong> To the
            maximum extent permitted by law, we disclaim all warranties, express or
            implied, including warranties of merchantability, fitness for a particular
            purpose, accuracy, and non-infringement.
          </P>
          <P>
            We do not warrant that the App will be uninterrupted, error-free, secure
            against unauthorised access, or that defects will be corrected. Your use of
            the App is at your own risk.
          </P>
        </Section>

        <Section title="10. Limitation of liability">
          <P>
            To the maximum extent permitted by law, we will not be liable for any
            indirect, incidental, special, consequential, or punitive damages, or for any
            loss of profits, revenue, data, goodwill, or business arising out of your use
            of (or inability to use) the App.
          </P>
          <P>
            Where liability cannot be excluded as a matter of law, our total aggregate
            liability for any claim arising out of or relating to the App is limited to
            the greater of (a) the amount you paid us for the App in the twelve months
            preceding the event giving rise to the claim, or (b) £20.
          </P>
        </Section>

        <Hr />

        <Section title="11. Termination">
          <P>
            We may suspend or terminate your access to the App at any time for violation
            of these Terms or for any reason at our reasonable discretion. Provisions
            that by their nature should survive termination (e.g. content licence,
            disclaimers, limitation of liability) will continue to apply.
          </P>
        </Section>

        <Section title="12. Changes to these Terms">
          <P>
            We may update these Terms from time to time. Material changes will be
            announced in-app or by email. Continued use of the App after a change becomes
            effective constitutes acceptance of the revised Terms. If you do not agree,
            you should stop using the App and may delete your account.
          </P>
        </Section>

        <Section title="13. Governing law">
          <P>
            These Terms are governed by the laws of France, without regard to its
            conflict-of-law principles. Any dispute arising out of or relating to these
            Terms will be resolved in the competent courts of Paris, France, unless
            applicable mandatory consumer-protection laws give you the right to bring a
            claim in your country of residence.
          </P>
        </Section>

        <Section title="14. Contact">
          <P>
            Questions about these Terms? Email{" "}
            <a href="mailto:margot@margotwardrobe.com" className="underline hover:text-peach">
              margot@margotwardrobe.com
            </a>
            .
          </P>
          <P>
            <Strong>YAVREN</Strong>
          </P>
        </Section>

        <Hr />

        <p className="font-sans text-[12px] text-ink3 tracking-tight7 mt-12">
          By using Margot you confirm you have read, understood, and agreed to these
          Terms of Service and our{" "}
          <Link href="/privacy" className="underline hover:text-peach">
            Privacy Policy
          </Link>
          .
        </p>
      </article>
    </main>
  );
}

function Section({ title, children }: { title?: string; children: React.ReactNode }) {
  return (
    <section className="mt-8 mb-6">
      {title && (
        <h2 className="font-display font-normal text-ink opsz-96 text-[22px] leading-[1.2] tracking-tight5 mb-3">
          {title}
        </h2>
      )}
      {children}
    </section>
  );
}

function Sub({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-5 mb-3">
      <h3 className="font-display italic text-ink2 opsz-96 text-[16px] leading-[1.3] tracking-tight5 mb-2">
        {title}
      </h3>
      {children}
    </div>
  );
}

function P({ children, className }: { children: React.ReactNode; className?: string }) {
  return (
    <p
      className={`font-sans text-[15px] leading-[1.65] text-ink2 tracking-tight7 [text-wrap:pretty] my-3 ${className ?? ""}`}
    >
      {children}
    </p>
  );
}

function Ul({ children }: { children: React.ReactNode }) {
  return (
    <ul className="font-sans text-[15px] leading-[1.65] text-ink2 tracking-tight7 list-disc ml-5 my-3 space-y-1.5">
      {children}
    </ul>
  );
}

function Li({ children }: { children: React.ReactNode }) {
  return <li className="[text-wrap:pretty]">{children}</li>;
}

function Strong({ children }: { children: React.ReactNode }) {
  return <strong className="font-semibold text-ink">{children}</strong>;
}

function Hr() {
  return <hr className="my-10 border-0 h-px bg-warm2" />;
}
